---
title: "Notes on network and generation"
output: pdf_document
---

Suppose we have one infected individual and one susceptible individual. Infected individual makes effective contact at a constant rate $\beta$ and has a constant recovery rate of $\lambda$. Then, we can write the probability that the susceptible remains uninfected at time $t$ as follows:

$$
s(\tau)= \exp(-\beta \int_{t = 0}^\tau \exp(-\lambda t) dt)
$$

Solving the integral, we have

$$
\begin{aligned}
s(\tau) = \exp\left(-\frac{\beta}{\lambda} (1 - \exp(-\lambda \tau)) \right)\\
\end{aligned}
$$

Define $K(\tau) = F(\tau) \beta$ as the rate of secondary case, where $F(\tau) = \exp(-\lambda \tau)$ is the probability that an infectious individual has not recovered $t$ time units after infection.

We define network generation interval as follows:

$$
g(\tau) = \frac{K(\tau)s(\tau)}{\int_0^\infty K(\tau)s(\tau)d\tau}
$$

which can be simplified into

$$
g(\tau) = \frac{F(\tau)s(\tau)}{\int_0^\infty F(\tau)s(\tau)d\tau}
$$

Let's try to solve the integral... First, let's do substitution: 

$$
\begin{aligned}
dF &= -\lambda \exp(-\lambda \tau) d\tau\\
&= -\lambda F d\tau
\end{aligned}
$$

Substitute it:

$$
\begin{aligned}
&\quad \int_0^\infty F(\tau) s(\tau) d\tau\\
&= -\frac{1}{\lambda} \int_1^0 \exp(-\frac{\beta}{\lambda} (1 - F)) dF\\
&= \frac{1}{\beta} \left[\exp(-\frac{\beta}{\lambda} (1 - F)) \right]_0^1\\
&= \frac{1}{\beta} \left(1 - \exp(-\frac{\beta}{\lambda}) \right)
\end{aligned}
$$

Therefore, the generation interval is

$$
g(\tau) = \beta \left(1 - \exp(-\frac{\beta}{\lambda}) \right)^{-1} \exp(-\lambda \tau) \exp\left(-\frac{\beta}{\lambda} (1 - \exp(-\lambda \tau)) \right)
$$

Comparison of intrinsic generation with network generation distribution for SIR model:

```{r network gen, fig.width = 6, fig.height = 6, echo=FALSE}
F <- function(t, lambda){
    exp(-lambda * t)
}

intrinsic.gen <- function(t, lambda){
    lambda * F(t, lambda)
}

network.gen <- function(t, beta, lambda){
    beta * (1 - exp(-beta/lambda))^(-1) * F(t, lambda) *
        exp(-beta/lambda * (1 - F(t, lambda)))
}

t <- seq(0, 5, 0.01)

plot(t, intrinsic.gen(t, 1), type = "l", col = "blue",
     ylab = "",
     xlab = "Time since infection")

for(i in 1:3){
    m <- 0.2 * 5^(i-1)
    lines(t, network.gen(t, m, 1), lty = i + 1)
}

arrows(1.5, 0.2, 1.1, 0.08, col = "red")
```

As we increase effective transmission rate, network generation follows the red arrow. Let's try to write a general equation.

In a homogeneous population, generation interval is defined s follows (Svensson 2015):

$$
g(\tau) = \frac{P(X + Y > \tau) - P(X > \tau)}{E(Y)}
$$

where $X$ is the duration of the latent period and $Y$ is the duration of the infection period. To check that it works, let's try $SEIR$ model where both latent and infectious periods are exponentially distributed with rate $\gamma$ and $\lambda$:

$$
\begin{aligned}
P(X + Y > \tau)&= 1 - \int_0^\tau \int_0^s f_Y (s - t) f_X(t) dt ds\\
&=1 - \int_0^\tau \int_0^s \lambda \exp(-\lambda(s - t)) \gamma \exp(-\gamma t) dt ds\\
&=1 - \int_0^\tau \gamma \lambda \exp(-\lambda s) [\exp((\lambda-\gamma) t)/(\lambda - \gamma)]_0^s ds\\
&=1 - \int_0^\tau \frac{\gamma \lambda}{\lambda - \gamma} \exp(-\lambda s) (\exp((\lambda-\gamma) s) - 1) ds\\
&= 1 - \frac{\gamma \lambda}{\lambda - \gamma} \int_0^\tau  (\exp(-\gamma s) - \exp(-\lambda s)) ds\\
&= 1 - \frac{\gamma \lambda}{\lambda - \gamma} \bigg[\exp(-\lambda s)/\lambda-\exp(-\gamma s)/\gamma \bigg]_0^\tau\\
&= 1 - \frac{1}{\lambda - \gamma} \bigg[\gamma \exp(-\lambda s)- \lambda \exp(-\gamma s) \bigg]_0^\tau\\
&= 1 - \frac{1}{\lambda - \gamma} \bigg[\gamma \exp(-\lambda \tau)- \lambda \exp(-\gamma \tau) - \gamma + \lambda \bigg]\\
&= \frac{\gamma \exp(-\lambda \tau)- \lambda \exp(-\gamma \tau)}{\gamma-\lambda}\\
\end{aligned}
$$

And we also have

$$
\begin{aligned}
P(X > \tau) &= 1 - \int_0^\tau \gamma \exp(-\gamma t) dt\\
&= 1 + (\exp(-\gamma t))_0^\tau\\
&= \exp(-\gamma \tau)
\end{aligned}
$$

Then,

$$
\begin{aligned}
\frac{P(X + Y > \tau) - P(X >\tau)}{E(Y)} &=\lambda \left(\frac{\gamma \exp(-\lambda \tau)- \lambda \exp(-\gamma \tau)}{\gamma-\lambda} - \exp(-\gamma \tau) \right)\\
&= \lambda\gamma \left(\frac{\exp(-\lambda \tau)- \exp(-\gamma \tau)}{\gamma-\lambda} \right)\\
\end{aligned}
$$

Got the same result as Svensson, which is a good sign. Now, how do we apply this to a network.. Going back to Trapman et al, we have the following survival function:

$$
\begin{aligned}
s(\tau) &= \exp\left(-\beta \left(\int_0^\tau F(t) dt \right) \right)\\
&= \exp\left(-\beta \left(\int_0^\tau P(X+Y>t)-P(X>t) dt \right) \right)\\
\end{aligned}
$$


